name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  GAMES_API_URL: "https://some-api-url"
  POSTGRES_URL: "postgresql://some-postgres-url"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun typecheck
      - uses: iamsauravsharma/create-dotenv@v1.2.2
      - run: bun docker

  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: survivor-pool-test
          POSTGRES_PASSWORD: pwd
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run test

  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Install Browsers
        run: bun playwright install --with-deps

      - name: Run Component Tests
        run: bun playwright test --shard ${{ matrix.shard }}

  db:
    name: Database Update
    runs-on: ubuntu-latest
    needs:
      - build
      - test-backend
      - test-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun drizzle
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
