name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun type-check
      - run: bun transpile
      - run: bun test

  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Setup Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('bun.lockb') }}

      - name: Install Cypress binary if not cached
        run: bun cypress install

      - name: Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

      - name: E2E Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: bun docker
          wait-on: "http://localhost:8080"
