name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun type-check
      - run: bun test
      - run: bun docker

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Setup Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package.json') }}

      - name: Install Cypress binary if not cached
        run: bun cypress install

      - name: Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true

  db:
    name: Database Migration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Run Migration Scripts on Test DB
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/db
          user: user
          password: password
          locations: classpath:src/migrations

      - name: Run Migration Scripts on Prod DB
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.POSTGRES_URL }}
          user: ${{ secrets.POSTGRES_USER }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          locations: classpath:src/migrations
