name: Tests

on:
  push:
    branches:
      - main

env:
  GAMES_API_URL: "https://some-api-url"
  POSTGRES_URL: "postgresql://some-postgres-url"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun typecheck
      - run: bun test
      - uses: iamsauravsharma/create-dotenv@v1.2.2
        env:
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      - run: bun docker

  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Setup Cypress cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package.json') }}

      - name: Install Cypress binary if not cached
        run: bun cypress install

      - name: Component Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          env: CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}

  db:
    name: Database Migration
    runs-on: ubuntu-latest
    needs:
      - test
      - cypress
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun drizzle
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
